### ISSUE TITLE
Add a page that can be sent to "newbies"

### ISSUE THREAD

**Issue by penn5** [small-tech/cleanuptheweb.org#2]
Ideally this page would have a nice intro to what tracking is, what used to happen, what happens now, why people should care, how to opt out on the client side, how to switch browser, a comparison of browsers, etc.

**Comment by aral** [comment]
@penn5 Thanks. I agree that a general page on these issues would be a good thing to have. However, the target for this site/page is developers. Which aspects of an introductory page (if any) would you think would be useful for web developers?
